root: true
parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 6
  sourceType: module

plugins:
- "@typescript-eslint"

rules:
  # "@typescript-eslint/naming-convention": warn
  # "@typescript-eslint/semi": warn
  # curly: warn
  # eqeqeq: warn
  # no-throw-literal: warn
  semi: [ 1, never ]
  curly: [ 1, multi-or-nest ]
  no-multiple-empty-lines: [ 1, { max: 1 } ]
